### ISSUE TITLE
пункт  "оформляем плагин"

### ISSUE THREAD

**Issue by tesla604** [systemo-biz/taxonomy-list-wp#1]
Собственно непонятный для меня пункт  "оформляем плагин" какой именно? 

Что такое плагины я знаю, а вот "оформляем плагин" - вводит в ступор.

**Comment by aiiddqd** [comment]
Это значит что задачу можно решить без плагина. Например вводом кода в тему.

Оформляем плагин - значит что задачу нужно решить через создание плагина. Оформленного по кодексу http://codex.wordpress.org/%D0%9D%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5_%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D0%B0

**Comment by tesla604** [comment]
Теперь понятно! Принялся изучать чтиво, как появятся вопросы с приминением на практике отпишу..
