### ISSUE TITLE
админка ругается...

### ISSUE THREAD

**Issue by tesla604** [systemo-biz/taxonomy-list-wp#2]
Приветствую!
 Все сделал как по  "todo", в админке в менюшке плагинов видно мой "горе плагин" :) 
но когда пытаюсь активировать выдает критическую ошибку и ругается на синтаксис на 2рой строке кода.
Не могу понять, в чем причина? Как мне прикрепить здесь файл что б вы (произвели вскрытие) посмотрели...

**Comment by aiiddqd** [comment]
Ну и я телепатические способности оставил в прошлой жизни.
Нужен снимок ошибки и ссылку на код.
О том как это делать написано тут http://wpcraft.ru/obmen-snimkami-e-krana-i-snippetami-koda-dlya-obshheniya/

**Comment by tesla604** [comment]
ок, принял щя будет, снимок сделать не проблема функция "printscrin" вроде для этого? а вот код зачем на "пастеби"н проще тут репозиторий создать. щя будет сделано!

**Comment by tesla604** [comment]
вот скрин - [http://itmages.ru/image/view/2102579/71714f36]
вот код - [http://pastebin.com/PW3hKqus]
прошу прощения за мою скорость сказал "щя" а получилось через 2-часа, свет выключали в районе...
не на |pastebin| все таки проще тут чет муторно с созданием репозитория или сказывается 10+ часов за монитором, не осилил ^_^

**Comment by aiiddqd** [comment]
читай внимательней инструкции.
у тебя мета данные плагина вне комментов. должно быть так:

<?php
/*
Plugin Name: list_taxonomy_cp
Plugin URI: http://
Description:
Version: 0.1
Author: tesla604
Author URI: http://http://tplagintax.zz.vc
*/

**Comment by aiiddqd** [comment]
и работать все равно не будет. надо выводить через шорткод. а для этого надо этот шорткод во первых описать функцией, а во вторых вставить на какую нибудь страницу.

**Comment by tesla604** [comment]
ясно, да раскомментировал осознано  подумав что сделал все правильно ___ ну буду знать!

**Comment by tesla604** [comment]
а какой функцией описывать шорт код?

**Comment by aiiddqd** [comment]
http://yandex.ru/yandsearch?text=%D1%88%D0%BE%D1%80%D1%82%D0%BA%D0%BE%D0%B4%D1%8B%20wordpress

**Comment by tesla604** [comment]
принял!

**Comment by aiiddqd** [comment]
долго, мне передать задачу?
